module.exports.states = {
  'active': 'a',
  'checked': 'ch',
  'disabled': 'd',
  'empty': 'e',
  'focus': 'f',
  'hover': 'h',
  'target': 't',
};

module.exports.media = {
  375: '>3',
  425: '>4',
  768: '>7',
  1024: '>10',
  1024: '>14',
};

module.exports.utils = {
  'Mx': ['margin-left', 'margin-right'],
  'My': ['margin-bottom', 'margin-top'],
  'Px': ['padding-left', 'padding-right'],
  'Py': ['padding-bottom', 'padding-top'],
};

module.exports.map = {
  'align-content': 'Ac',
  'align-items': 'Ai',
  'align-self': 'As',
  'all': 'All',
  'animation': 'A',
  'animation-delay': 'Animdel',
  'animation-direction': 'Animdir',
  'animation-duration': 'Animdur',
  'animation-fill-mode': 'Animfm',
  'animation-iteration-count': 'Animitc',
  'animation-name': 'Animn',
  'animation-play-state': 'Animps',
  'animation-timing-function': 'Animtf',
  'backface-visibility': 'Bfv',
  'background': 'Bg',
  'background-attachment': 'Bga',
  'background-blend-mode': 'Bgbm',
  'background-clip': 'Bgcp',
  'background-color': 'Bgc',
  'background-image': 'Bgi',
  'background-origin': 'Bgo',
  'background-position': 'Bgp',
  'background-repeat': 'Bgr',
  'background-size': 'Bgz',
  'border': 'Bd',
  'border-bottom': 'Bdb',
  'border-bottom-color': 'Bdbc'
  'border-bottom-left-radius': 'Bblr',
  'border-bottom-right-radius': 'Bbrr',
  'border-bottom-style': 'Bbs',
  'border-bottom-width': 'Bbw',
  'border-collapse': 'Bdcol',
  'border-color': 'Bdc',
  'border-left': 'Bdl',
  'border-left-color': 'Bdlc',
  'border-left-width': 'Bdlw',
  'border-radius': 'Bdrs',
  'border-right': 'Bdr',
  'border-right-color': 'Bdrc',
  'border-right-width': 'Bdrw',
  'border-spacing': 'Bdsp',
  'border-style': 'Bds',
  'border-top': 'Bdt',
  'border-top-color': 'Bdtc',
  'border-top-width': 'Bdtw',
  'border-width': 'Bdw',
  'bottom': 'B',
  'box-shadow': 'Bxsh',
  'color': 'C',
  'cursor': 'Cur',
  'display': 'D',
  'flex': 'Fx',
  'flex-basis': 'Fxb',
  'flex-direction': 'Fxd'
  'flex-grow': 'Fxg',
  'flex-shrink': 'Fxs',
  'flex-wrap': 'Fxw',
  'font': 'F',
  'font-family': 'Ff',
  'font-size': 'Fz',
  'font-style': 'Fs',
  'font-variant': 'Fv',
  'font-weight': 'Fw',
  'height': 'H',
  'justify-content': 'Jc',
  'left': 'L',
  'letter-spacing': 'Lsp',
  'line-height': 'Lh',
  'list-style-type': 'List',
  'margin': 'M',
  'margin-bottom': 'Mb',
  'margin-left': 'Ml',
  'margin-right': 'Mr',
  'margin-top': 'Mt',
  'max-height': 'Mah',
  'max-width': 'Maw',
  'min-height': 'Mih',
  'min-width': 'Miw',
  'opacity': 'Op',
  'order': 'Or',
  'outline': 'Out',
  'overflow': 'Ov',
  'overflow-x': 'Ovx',
  'overflow-y': 'Ovy',
  'padding': 'P',
  'padding-bottom': 'Pb',
  'padding-left': 'Pl',
  'padding-right': 'Pr',
  'padding-top': 'Pt',
  'pointer-events': 'Pe',
  'position': 'Pos',
  'resize': 'Rsz',
  'right': 'R',
  'table-layout': 'Tbl',
  'text-align': 'Ta',
  'text-align-last': 'Tal',
  'text-decoration': 'Td',
  'text-decoration-color': 'Tdc',
  'text-decoration-style': 'Tds',
  'text-indent': 'Ti',
  'text-overflow': 'Tov',
  'text-shadow': 'Tsh',
  'text-transform': 'Tt',
  'top': 'T',
  'transform': 'Trf',
  'transform-origin': 'Trfo',
  'transform-style': 'Trfs',
  'transition': 'Trs',
  'transition-delay': 'Trsdel',
  'transition-duration': 'Trsdur',
  'transition-property': 'Trsp',
  'transition-timing-function': 'Trstf',
  'user-select': 'Us',
  'vertical-align': 'Va',
  'visibility': 'Vi',
  'white-space': 'Whs',
  'width': 'W',
  'word-break': 'Wdb',
  'word-spacing': 'Wds',
  'word-wrap': 'Wdw',
  'z-index': 'Z',
};
